version: "3"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    networks:
      - app-network
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MONGO_INITDB_USERNAME=${DATABASE_USERNAME}
      - MONGO_INITDB_PASSWORD=${DATABASE_PASSWORD}

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    networks:
      - app-network
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=${DATABASE_PORT}
      - ME_CONFIG_BASICAUTH_USERNAME=${DATABASE_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${DATABASE_PASSWORD}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DATABASE_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DATABASE_PASSWORD}
    depends_on:
      - mongodb
networks:
  app-network:
    driver: bridge